# Generated by Django 5.1 on 2024-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Галерея товаров', 'verbose_name_plural': 'Галереи товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(upload_to='product preview images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='product gallery images'),
        ),
    ]
